# Generated by Django 4.0.3 on 2022-05-23 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ainfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('optional', models.CharField(choices=[('O', 'Optional'), ('N', 'Not Optional')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Year_of_study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('enrolled', models.ManyToManyField(through='ainfo.Enrollment', to='ainfo.student_details')),
                ('faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chief_of_department', models.BooleanField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.faculty')),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.titles')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Optional_preferences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.student_details')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.student_details'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='year_of_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.year_of_study'),
        ),
        migrations.CreateModel(
            name='Curriculum_course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.course')),
                ('curriculum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.curriculum')),
            ],
        ),
        migrations.AddField(
            model_name='curriculum',
            name='courses',
            field=models.ManyToManyField(through='ainfo.Curriculum_course', to='ainfo.course'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='year_of_study_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.year_of_study'),
        ),
        migrations.CreateModel(
            name='CourseProposition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.course')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ainfo.teacher_details')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='ainfo.Optional_preferences', to='ainfo.student_details'),
        ),
    ]
